Sprint02 us47 section full comp
WildCodeSchool/orleans-0219-php-petanque pull request #10
Opened 2019-04-15 09:27 UTC by xNousex

2019-04-15 13:13 UTC, open-it requested changes

2019-04-15 13:13 UTC, open-it commented on src/View/Common/_footer.html.twig
> +<div class="container-fluid footer_stylish text_footer">
Pourquoi j'ai le footer dans le Show Event ?

2019-04-15 13:51 UTC, open-it approved these changes

2019-04-16 07:05 UTC, sblondeau requested changes

2019-04-16 07:05 UTC, sblondeau commented on public/assets/css/style.css
> +        /*     background-color: #fff;*/
code commenté

2019-04-16 07:05 UTC, sblondeau commented on src/Controller/EventController.php
> +            'mainTitle' => 'Vie du club',
pourquoi avez vous des mainTitle et mainSubtitle ? ça ne devrait pas etre dans le twig direct ? car c'est de la vue

2019-04-16 07:05 UTC, sblondeau commented on src/Model/EventManager.php
> +        WHERE evenement.id=:id";
ouch la requete... le nommage des champs n'est pas extra (genre les evtcategory pourrait juste être category, pas la peine de reprefixer partout les champs du nom de la table, c'est redondant et tu le corriges par des alias inutiles du coup), mais bon...
pareil utilisez des alias courts pour les noms de table, par ex c pour category, dpour departement, etc. ça va alléger un peu la requete

2019-04-16 07:15 UTC, xNousex commented on src/Controller/EventController.php
> +            'mainTitle' => 'Vie du club',
Il s'agit d avoir un texte dynamique dans le teaser suivant la page appelé

2019-04-16 09:30 UTC, sblondeau approved these changes

2019-04-16 09:30 UTC, merged