Sprint02 us08 hsec horaires
WildCodeSchool/orleans-0219-php-petanque pull request #13
Opened 2019-04-15 13:27 UTC by sylvainaubert

Pull Request, SPRINT02_US08_HsecHoraire, section "horaires" de l'index.

2019-04-15 13:54 UTC, open-it approved these changes

2019-04-16 09:40 UTC, sblondeau requested changes

2019-04-16 09:40 UTC, sblondeau commented on public/assets/css/style.css
> +        /*     background-color: #fff;*/
code commenté

2019-04-16 09:40 UTC, sblondeau commented on src/View/Home/index.html.twig
>                      <div class="card card_vosenvies">
les noms de classe en anglais comme tout le reste !

2019-04-16 09:40 UTC, sblondeau commented on src/View/Home/index.html.twig
> +                            <td data-title="Après-midi :">14h00 -> 19h30</td>
bizarre une flèche "->" pour le rendu non ?

2019-04-16 09:46 UTC, sylvainaubert commented on src/View/Home/index.html.twig
> +                            <td data-title="Après-midi :">14h00 -> 19h30</td>
Ça va changer pour des "De [...] à" dans la User Story qui vient.

2019-04-16 12:13 UTC, sblondeau requested changes

2019-04-16 12:13 UTC, sblondeau commented on src/View/Home/index.html.twig
> +        <div class="container">
j'avais pas fait attention, mais tu n'as pas à recréer un container à chaque row.
ta classe container peut-etre mise direct sur la section normalement

2019-04-16 12:37 UTC, sylvainaubert commented
Ok. Doublons de div corrigé.

2019-04-16 12:40 UTC, sblondeau requested changes

2019-04-16 12:40 UTC, sblondeau commented on src/View/Home/index.html.twig
> +        <div class="container">
non du coup tu devrais pouvoir mettre la classe container direct sur la section, et te passer également de ce div qui ne sert à rien

2019-04-16 12:53 UTC, sylvainaubert commented on src/View/Home/index.html.twig
> +        <div class="container">
Oui, tu as raison. J'ai viré la div container inutile.

2019-04-16 13:57 UTC, sylvainaubert commented
Ajustement des class container entre section et div fait.

2019-04-16 14:10 UTC, sblondeau approved these changes

2019-04-16 14:24 UTC, merged