Sprint02 us51 ad comp full page
WildCodeSchool/orleans-0219-php-petanque pull request #15
Opened 2019-04-15 15:15 UTC by xNousex

Liste des évènements pour administration

2019-04-15 15:40 UTC, open-it requested changes

2019-04-15 15:40 UTC, open-it commented on src/Model/EventManager.php
> +    public function selectAllEvents(): array
pourquoi j'ai cette methode alors que dans l'index vous appelez la methode selectEventsToCome ?

2019-04-15 15:43 UTC, xNousex commented on src/Model/EventManager.php
> +    public function selectAllEvents(): array
En effet une erreur. Désolé

2019-04-16 09:53 UTC, sblondeau requested changes

2019-04-16 09:53 UTC, sblondeau commented on src/Controller/EventController.php
> +    public function eventsadmin()
si cette méthode doit gérer la partie "admin" des event, elle devrait etre dans un autre controller que celui qui gère les event coté "visiteurs".
Donc faire un AdminEventController et une méthode index()

2019-04-16 14:13 UTC, sblondeau approved these changes

2019-04-16 15:58 UTC, sblondeau approved these changes

2019-04-16 15:58 UTC, merged