Sprint02 us06 hsec qui
WildCodeSchool/orleans-0219-php-petanque pull request #28
Opened 2019-04-16 13:49 UTC by AngelRionCervi

2019-04-16 14:26 UTC, sblondeau requested changes

2019-04-16 14:26 UTC, sblondeau commented on src/View/Home/index.html.twig
> +                        <div class="qui_desc_wrap text-left">
on ne créé pas une page avec du lorem ipsum, mais uniquement avec du texte "final" sinon la page n'est pas "terminée" !

2019-04-17 14:09 UTC, sblondeau requested changes
on est d'accord que les images des personnes ça sera qqchose d'administrable ? donc si les images ne sont pas "statiques", il ne faut pas les envoyer sur le serveur, les images dans le dossier images/members devrait donc être non versionnées

2019-04-24 10:04 UTC, sblondeau requested changes

2019-04-24 10:04 UTC, sblondeau commented on src/Controller/HomeController.php
> +        $membersManager = new MemberManager();
$memberManager

2019-04-25 12:33 UTC, open-it approved these changes

2019-04-25 14:21 UTC, sblondeau requested changes
les images ne doivent pas etre versionnées !!!!!!!!

2019-04-26 06:52 UTC, sblondeau requested changes
mettre dans le gitignore ne suffit pas à déversionner des images qui l'ont déjà été une fois, comme on en a déjà parlé.
il faut que tu fasses aussi un git rm --cached sur les images dans ces 2 dossiers, sinon elles sont tjs versionnées comme là...

2019-04-26 10:40 UTC, sblondeau approved these changes

2019-04-26 12:46 UTC, closed without merging