Sprint03 us57 ad remove comp event
WildCodeSchool/orleans-0219-php-petanque pull request #39
Opened 2019-04-23 10:21 UTC by xNousex

Mise en place de la suppresssion d'évènement dans la partie admin des évènements

2019-04-23 14:27 UTC, sblondeau requested changes

2019-04-23 14:27 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +        $eventManager = new EventManager();
pourquoi instancie tu 2 fois le EvenManager ?

2019-04-23 14:27 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +        $events = $eventManager->selectEventsToCome();
et non ici, une fois la suppression faites, tu fais une redirection (header Location) vers la page affichant l'index de l'admin, et tu ne fais donc pas de render)

2019-04-23 14:27 UTC, sblondeau commented on src/View/Event/indexadmin.html.twig
> +                        <td><a class="btn btn-danger w-100" href="{{ base_path ~ directory }}/AdminEvent/delete/{{ event.id }}" role="button">Enlever</a></td>
jamais de suppression en GET ! il faut faire un formulaire et passer en POST pour éviter des failles de sécurité comme on l'a expliqué

2019-04-23 16:16 UTC, AngelRionCervi approved these changes

2019-04-24 10:17 UTC, sblondeau requested changes

2019-04-24 10:17 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +        if (empty($errors)) {
ça c'est à l'intérieur de ton if POST
du coup pas la peine d'initialiser $id = 0

2019-04-24 10:17 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +        if (empty($errors)) {
faire un clean sur le $_POST

2019-04-24 10:17 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +        if ($_SERVER['REQUEST_METHOD'] === 'GET') {
à simplifier comme discuté
$alertResult = $_GET['success'] ?? false;

2019-04-24 12:06 UTC, AngelRionCervi approved these changes

2019-04-24 12:12 UTC, AngelRionCervi approved these changes

2019-04-24 13:48 UTC, sblondeau requested changes

2019-04-24 13:48 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +        $alertResult = isset($_GET['status']) ? true : false ;
dans ce cas, mets $alertResult = isset($_GET['status']); car isset() renvoie soit true, soit false, la condition ternaire ne sert donc à rien ici

2019-04-24 15:30 UTC, AngelRionCervi approved these changes

2019-04-24 21:23 UTC, sblondeau approved these changes

2019-04-25 10:20 UTC, sylvainaubert approved these changes

2019-04-25 12:29 UTC, open-it approved these changes
la PR n'est pas parfait et devrait être refusée. Les messages d'alertes n'ont pas d'apostrophes et il y a du code lié à l'index (affichage) et non au delete qui est le sujet de la US.

2019-04-25 12:30 UTC, merged