Sprint03 us56 ad modify comp event
WildCodeSchool/orleans-0219-php-petanque pull request #40
Opened 2019-04-23 13:09 UTC by xNousex

Modification d'un évènement sportif dans la partie admin

2019-04-23 14:32 UTC, sblondeau requested changes

2019-04-23 14:32 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +            if (empty($id) || $id < 0) {
ce n'est pas nécessaire comme vérif, pour vérifier <0 spécifiquement plutot qu'autre chose ? en fait il faudrait plutot vérifier dans ce cas si l'id existe bien ou non en BDD (avec un selectOneById AVANT de faire l'update, si ça ne te renovoie rien, alors tu gères l'erreur

2019-04-23 14:32 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +                return $this->twig->render('Event/indexadmin.html.twig', [
une redirection header Location plutot (sinon pb rafraichissement car ton $_POST ne sera pas vide)

2019-04-23 14:32 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +                    'editsuccess' =>true,
et gestion de la notification de succès par $_SESSION comme on a vu

2019-04-23 14:32 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +        } else {
ce else ne sert pas à grand chose car tu auras fais le header Location avant dans le cas d'une soumission

2019-04-23 16:12 UTC, xNousex commented on src/Controller/AdminEventController.php
> +        } else {
Je suis obligé de le faire pour la première récupération de l'évènement et pour remttre les données du Post si c est un retour d'erreur

2019-04-23 16:15 UTC, AngelRionCervi approved these changes

2019-04-24 10:20 UTC, sblondeau requested changes

2019-04-24 10:20 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +                header('Location:/event/show/' . $id . '/?status=success&&type=admin');
un seul &

2019-04-24 10:20 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +                header('Location:/event/show/' . $id . '/?status=success&&type=admin');
mettre un exit() après le header

2019-04-24 15:29 UTC, AngelRionCervi approved these changes

2019-04-25 12:44 UTC, open-it requested changes

2019-04-25 12:44 UTC, open-it commented on src/Controller/AdminEventController.php
> +        } else {
j'avoue que je n'ai pas compris non plus pourquoi ce else ? Tu peux tout simplement mettre ces deux lignes avec les autres (juste sans le else en fait)

2019-04-25 12:44 UTC, open-it commented on src/Controller/EventController.php
> +        $alertResult = isset($_GET['status']);
pourquoi j'ai du code du show alors qu'on traite de l'update ?

2019-04-25 12:44 UTC, open-it commented on src/View/Event/show.html.twig
> +        {% if statusAlert == true %}
pareil ? Pourquoi du show alors qu'on fait de l'update ? A la rigueur le index pour la redirection mais la j'ai update, index et show

2019-04-25 12:47 UTC, xNousex commented on src/Controller/EventController.php
> +        $alertResult = isset($_GET['status']);
Parc que ca renvoie vers la fiche unique de l'évènement pour avoir un apercu de l'ensemble des infos saisies.
Il y a un bouton de renvoi vers la liste des évnements administrables

2019-04-25 12:47 UTC, xNousex commented on src/View/Event/show.html.twig
> +        {% if statusAlert == true %}
Parc que ca renvoie vers la fiche unique de l'évènement pour avoir un apercu de l'ensemble des infos saisies.
Il y a un bouton de renvoi vers la liste des évnements administrables

2019-04-25 14:23 UTC, sblondeau requested changes

2019-04-25 14:23 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +        } else {
en fait à relire, la bonne solution serait de mettre ces lignes à la place de l'initialisation par un tableau vide de $eventData tout en haut de la méthode

2019-04-25 16:10 UTC, xNousex commented on src/Controller/AdminEventController.php
> +        } else {
Je voudrais bien étudier cette partie avec toi car je ne vois pas le souci en fait suivant la dynamique de la fonction

2019-04-28 22:39 UTC, sblondeau requested changes

2019-04-28 22:39 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +        } else {
ça n'empêche pas la méthode de fonctionner, c'est juste que ça évite ce else inutile, déplace le contenu ligne 113 et ça sera bon ;-)

2019-04-29 07:00 UTC, sblondeau approved these changes

2019-04-29 07:23 UTC, merged