Sprint02 us55 ad add comp event fix
WildCodeSchool/orleans-0219-php-petanque pull request #44
Opened 2019-04-23 14:55 UTC by xNousex

Mise en place de la redirection avec gestion du Get pour passer un message d'alert dans le cas d'une administration et gestion de la rediction vers la liste administration ou de visiteur suivant le cas

2019-04-24 10:24 UTC, sblondeau requested changes

2019-04-24 10:24 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +                header('Location:/event/show/' . $id . '/?status=success&&type=admin');
un seul &

2019-04-24 10:24 UTC, sblondeau commented on src/Controller/EventController.php
> +        if ($_SERVER['REQUEST_METHOD'] === 'GET') {
à simplifier comme pour l'autre PR

2019-04-24 10:24 UTC, sblondeau commented on src/View/Event/show.html.twig
> +                        ver la liste d'évènements d'administration</a>
vers

2019-04-24 10:24 UTC, sblondeau commented on src/View/Event/show.html.twig
> +                        ver la liste d'évènements</a>
vers

2019-04-25 12:50 UTC, open-it requested changes
je ne vois pas la PR correspondante dans le projet sur github ? Je ne peux donc pas dire si elle est conforme.

2019-04-25 14:21 UTC, sylvainaubert approved these changes

2019-04-25 14:27 UTC, sblondeau requested changes

2019-04-25 14:27 UTC, sblondeau commented on src/View/Event/show.html.twig
> +                {% if adminStatus == true %}
hum... non gère des pages différentes pour la vue visiteur (qui doit etre joiie et afficher les infos utilies pour le visiteur)
et une vue pour l'admin (plus dans l'efficacité, affichant les infos utiles pour l'admin).

2019-04-25 14:27 UTC, sblondeau commented on src/View/Event/show.html.twig
> +                    <a class="btn comp-button-moreinfo " href="{{ base_path ~ directory }}/Event/index" role="button">Retour
le base_path et directory sont inutiles non ?

2019-04-25 16:13 UTC, xNousex commented on src/View/Event/show.html.twig
> +                {% if adminStatus == true %}
Non j'avoue je ne comprends pas l'intérêt. L'administrateur veut avoir un visu résultat de la modification ou de l'ajout. Il me permet cohérent de réutiliser la vue "visiteur" pourn'avoir à gérer qu un rendu identique.

2019-04-26 06:59 UTC, sblondeau requested changes

2019-04-26 06:59 UTC, sblondeau commented on src/View/Event/show.html.twig
> +                {% if adminStatus == true %}
non car tu es dans 2 parties distinctes du site généralement (l'une nécessitant une connexion, l'autre non)
et au niveau de l'affichage, tu veux souvent des infos différentes (plus exhaustive dans le cas d'un admin, avec peut etre des options pour gérer l'événement). Ca évite de mélanger dans un meme controller la partie visiteur et admin;
Tu devrais avoir un EventController et un AdminEventController bien distinct

2019-04-26 12:10 UTC, sblondeau approved these changes

2019-04-28 22:32 UTC, merged