Sprint03 us03 header fix
WildCodeSchool/orleans-0219-php-petanque pull request #51
Opened 2019-04-25 10:09 UTC by xNousex

Mise à jour des liens de la navbar
Mise à jour des images de fond du header
Mise à jour de _header TWIG pour faire varier les Titles h1 h2 par variables pour les appels de vue TWIG

2019-04-25 10:13 UTC, sylvainaubert approved these changes

2019-04-25 12:21 UTC, open-it requested changes

2019-04-25 12:21 UTC, open-it commented on src/View/sublayout_visitor.html.twig
> +    {% include 'Common/_header.html.twig' with {headerMainTitle: headerMainTitle, headerSubTitle: headerSubTitle, smallHeader:  smallHeader} %}
je pense que les variables passées via le with ne sont pas nécessaire.

2019-04-25 12:36 UTC, xNousex commented on src/View/sublayout_visitor.html.twig
> +    {% include 'Common/_header.html.twig' with {headerMainTitle: headerMainTitle, headerSubTitle: headerSubTitle, smallHeader:  smallHeader} %}
La solution trouvé est la seule possible d'après les études de forum pour le passage de données dans un  { Block } étentu d'un {block} étendu d'un layout général contenant un include pour passer un h1 / h2
La seule solution alternative était de le passer directement en paramètres direct du render mais Sylvain ne souhaitait pas cette solution.

2019-04-25 13:01 UTC, AngelRionCervi approved these changes

2019-04-25 14:35 UTC, sblondeau commented on src/View/Common/_header.html.twig
> +                    <a class="nav-link" href="{{ base_path ~ directory }}/wishes/index">Vos Envies</a>
base path et directory utiles ?

2019-04-25 16:24 UTC, xNousex commented on src/View/Common/_header.html.twig
> +                    <a class="nav-link" href="{{ base_path ~ directory }}/wishes/index">Vos Envies</a>
@sblondeau
Non il est nécessaire car le routeur ne suffit pas à faire la redirection (ou alors il y a une feinte)
Si je suis dans la page .../event/show/5, je clique sur le bouton. Si je ne mets que Event/Index, il va me rediriger vers /event/event/index .... qui n'existe pas.... d'où l'intéret du base_path.
Le base_path fonctionne parfaitement bien fonctionnellement. As tu une autre solution?

2019-04-25 17:13 UTC, AngelRionCervi approved these changes

2019-04-26 07:02 UTC, sblondeau approved these changes

2019-04-26 07:04 UTC, sblondeau commented on src/View/Common/_header.html.twig
> +                    <a class="nav-link" href="{{ base_path ~ directory }}/wishes/index">Vos Envies</a>
/wishes/index ou /event/show/5 suffit normalement 
mais je vois que tu as fais un fix à ce propos ?

2019-04-26 09:37 UTC, AngelRionCervi approved these changes

2019-04-28 22:33 UTC, sblondeau approved these changes

2019-04-29 07:01 UTC, merged