Sprint03 us18 sec page qui
WildCodeSchool/orleans-0219-php-petanque pull request #63
Opened 2019-04-29 08:31 UTC by AngelRionCervi

2019-04-29 08:33 UTC, sylvainaubert approved these changes

2019-04-29 10:32 UTC, sblondeau requested changes
j'ai des partners et des members dans la meme PR, ça ne devrait pas passer, mais bon, je vais fermer l'oeil là dessus si tu corriges les autres points

2019-04-29 10:32 UTC, sblondeau commented on src/Model/SponsorrManager.php
> +class SponsorrManager extends AbstractManager
PartnerManager !!! et non pas sponsor avec 2 R, je ne ferai pas passer la PR en l'état...

2019-04-29 10:32 UTC, sblondeau commented on src/View/Member/index.html.twig
> +                                Lorem ipsum dolor sit amet, consectetur
pas de lorem ipsum ! tu as bien un champ description dans ta table ? c'est ça qui doit etre ici

2019-04-29 20:44 UTC, sblondeau requested changes
dsl mais le nommage des variable c'est n'importe quoi...
il faut être vraiment vraiment vraiment plus rigoureux là dessus.

2019-04-29 20:44 UTC, sblondeau commented on src/Model/MemberManager.php
> +        $descriptions = array_map(function ($m) {
pas d'abbreviation dans les noms de variables. Premier cours PHP qui date de la semaine 2... Répété 500 fois depuis... 
c'est pas parce que c'est le dernier jour de PR qu'il faut push n'importe quoi, ça ne passera pas et on perd bêtement du temps tous les deux !

2019-04-29 20:44 UTC, sblondeau commented on src/Controller/MemberController.php
> +        $member = $memberManager->selectAll();
$members , c'est un tableau avec plusieurs membres

2019-04-29 20:44 UTC, sblondeau commented on src/Controller/MemberController.php
> +        for ($x=0; $x<count($member); $x++) {
$members
là tu peux faire un foreach ($members as $member) plutot

2019-04-29 20:44 UTC, sblondeau commented on src/Controller/MemberController.php
> +        $partner = $partnerManager->selectAll();
$partners

2019-04-29 20:44 UTC, sblondeau commented on src/Controller/MemberController.php
> +            'members' => $member,
et là tu vois en plus tu me fais un 'member**s**' => $member et ça n'a pas l'air de te choquer

2019-04-29 20:44 UTC, sblondeau commented on src/Model/MemberManager.php
> +        $descriptions = array_map(function ($m) {
en plus pour le coup le array_map ne me semble pas super utile

2019-04-29 20:44 UTC, sblondeau commented on src/Model/MemberManager.php
> +        $queryResult = $this->getTopMembers();
$topMembers = $this->getTopMembers me semble plus adapté question nommage

2019-04-29 20:44 UTC, sblondeau commented on public/assets/css/style.css
> +   /* max-width: 250px;
code commenté

2019-04-30 08:00 UTC, sylvainaubert approved these changes

2019-04-30 08:26 UTC, sblondeau approved these changes

2019-04-30 09:08 UTC, sylvainaubert approved these changes

2019-04-30 09:14 UTC, merged