Sprint04 us80 ad pic article
WildCodeSchool/orleans-0219-php-petanque pull request #68
Opened 2019-04-29 09:34 UTC by xNousex

Administration de la galerie photo

2019-04-29 09:41 UTC, sylvainaubert approved these changes

2019-04-29 10:47 UTC, sblondeau requested changes

2019-04-29 10:47 UTC, sblondeau commented on src/Controller/AdminPictureArticleController.php
> +                        if (!in_array($_FILES['upload']['type'][$i], $allowedFormats)) {
non tu as un elseif en trop
tu fais if !in_array($_FILES['upload']['type'][$i], $allowedFormats
=> $errors[] = format non supporté

if (($_FILES['upload']['size'][$i] > $maxSize)
=> $errors[]=taille > $tailleMax

if (empty($errrors))
=> le reste du traitement

2019-04-29 10:47 UTC, sblondeau commented on src/Controller/AdminPictureArticleController.php
> +                        if (!in_array($_FILES['upload']['type'][$i], $allowedFormats)) {
pas besoin de construire X fois ce tableau $files juste pour gérer les clés uploaded et uploadederror

2019-04-29 10:47 UTC, sblondeau commented on src/Controller/AdminPictureArticleController.php
> +        if (isset($_SESSION['uploadfiles'])) {
je ne vois pas trop à quoi te sers cette session

2019-04-29 10:47 UTC, sblondeau commented on src/View/Article/adminshowpicture.html.twig
> +        {% if not uploadedfiles is empty %}
ah... euh je pense que tu fais bien trop compliqué au niveau de la gestion des messages d'erreurs... avec la SESSION, le nombre d'erreur, etc.

2019-04-29 13:37 UTC, sylvainaubert approved these changes

2019-04-29 20:45 UTC, sblondeau approved these changes

2019-04-30 07:36 UTC, sylvainaubert approved these changes

2019-04-30 08:25 UTC, merged