Sprint04 us85 ad pic article delete
WildCodeSchool/orleans-0219-php-petanque pull request #77
Opened 2019-04-30 10:18 UTC by xNousex

Image galerie suppression image

2019-04-30 10:23 UTC, sylvainaubert approved these changes

2019-04-30 10:52 UTC, sblondeau requested changes

2019-04-30 10:52 UTC, sblondeau commented on src/Controller/AdminPictureArticleController.php
> +            header('Location:/AdminPictureArticle/showpicture/' . $article_id. '?status=deletesuccess');
il faut ajouter la suppression du fichier image également sinon il restera sur le serveur indéfiniment !
utilise unlink() pour cela

2019-05-01 07:43 UTC, sylvainaubert approved these changes

2019-05-01 11:55 UTC, sblondeau approved these changes

2019-05-01 11:55 UTC, merged