Sprint04 us86 article fix
WildCodeSchool/orleans-0219-php-petanque pull request #84
Opened 2019-04-30 15:11 UTC by xNousex

Mise au point du système d image par défaut pour les articles

2019-04-30 15:13 UTC, sylvainaubert approved these changes

2019-04-30 15:49 UTC, sblondeau requested changes

2019-04-30 15:49 UTC, sblondeau commented on src/View/Home/index.html.twig
>                                          <h4 class="card-title text-center">{{ articles[0].title }}</h4>
non ça ne va pas là, tu répètes 3 fois le meme code HTML, il faut plutot boucles sur articles

2019-05-01 11:55 UTC, sblondeau approved these changes

2019-05-01 11:55 UTC, merged